### ISSUE TITLE
Plans to split to multiple repositories?

### ISSUE THREAD

**Issue by thanpolas** [bigcompany/resources#72]
This repo is unpractical both for maintaining and installing.

The installed package is 40mb+, it'd be a rare occasion if someone wanted to use more than a couple of the resources...

With your permission i can break up all the resources into separate repositories maintaining commit history, then you'd need to perform `npm publish` on each. This repo would then be a directory / index for all available resource packages.

**Comment by Marak** [comment]
If you look at https://github.com/bigcompany you'll see this is already in
the process of being done.

**Comment by thanpolas** [comment]
I noticed it with `email`, didn't look like a bulk process to me, that's why i ask.

Wouldn't it be helpful if you prefixed all repositories with `resource-` ?

**Comment by Marak** [comment]
Went ahead and renamed the repos so resources to start with `resource-`

**Comment by Marak** [comment]
@thanpolas 

Yes, you have my permission to split them up. Any help moving towards version `0.5.x` would be appreciated. 

The major change would be resources now depend on `resource` engine `0.5.x` which uses http://mschema.org 

All resources' schemas should be moved into new schema packages.

**Comment by thanpolas** [comment]
I started work on the `queue` resource, repo at [thanpolas/resource-queue](https://github.com/thanpolas/resource-queue).

Please review the last commits on the repo. I prefer the mschema to exist in the same repo, instead of being one more npm package. I saw you used an npm package for the resource-\* stubs you are working on... i don't think we should add more complexity to the environment.

I added some OSS boilerplate and upgraded to `resource@0.5.2`, here are my issues so far:
1. In `index.js` of the resource [you add a description](https://github.com/bigcompany/resources/blob/master/queue/index.js#L4) using the path `queue.schema.description` ... how is this implemented in resource@0.5.2 ?
2. In mschema there is no `description` field, there are values in the original queue schema for description.
3. In mschema there is no `default` field. 
4. When moving source to be a controller, how are the method's properties, descriptions and other keys transported? I failed to find a way from current examples... e.g. how [is this `push` declaration](https://github.com/bigcompany/resources/blob/master/queue/index.js#L54-L78) transported to a controller?

I failed to find a document for all the mschema's keywords, so maybe the keys are there, but i can't know.

I'll post more as i find them, i also lurk in #big @freenode

**Comment by thanpolas** [comment]
I have transported the codebase to use the new controllers scheme, you can [review the results in the lib/ folder](https://github.com/thanpolas/resource-queue/tree/master/lib).

The problem now is how to reference the `queue` object from within the method declarations in file `lib/queue-methods.js`. 

I think the `queue.take` calls can easily be replaced with the local method `methods.take`, same applies to other locally available methods. But i am not so sure how to handle the `queue.emit` calls...

Also i did a logic update, check [c27342](https://github.com/thanpolas/resource-queue/commit/c27342a3b226fe0c61bdc6d412aa2dda5737bb6b).

**Comment by Marak** [comment]
Glad to see the contributions, thank you! :+1: 

To answer your questions:
1. There should be no change in syntax.
2. In mschema you can add a `description` property as text wherever you need.
3. mschema supports `default` values. Test coverage for default values is [here](https://github.com/mschema/mschema/blob/master/test/default-values-test.js) The tests folder overall will be the best place to find mschema documentation.
4. I have reviewed your latest commits. Migration to separate `controller` is not quite right. In new resource engine we have separated specification from implementation. This means that resource methods should be designed in a such a way as they are individual modules that export _one_ function and do not require `resource` or use `resource.method` or `resource.property`. A good place to see an example of this is [the user resource](https://github.com/bigcompany/resource-user/blob/master/index.js#L6) 

The mapping of methods to the resource is automatic based on the mschema's specified `input` and `output` properties. https://github.com/mschema/user/blob/master/index.js#L35 The resource engine will call `resource.method` for every exported controller method listed in the schema.

**Comment by thanpolas** [comment]
oh i totally missed the `resource.method` property!

I see now... there is no `output` prop in the user file... what would the syntax be?

**Comment by Marak** [comment]
As for putting the schema inside the project, I agree. I started to create individual repos and modules for every schema at https://github.com/mschema. I agree it's too much complexity keeping separate repos for the schemas.

Let's put the schema for each resource inside the root of resource repo. Using the naming convention `foo.mschema.js` is good.

**Comment by Marak** [comment]
If there is no output, it should default to `function(err, result)`... Where result is of type any.

Test coverage for this behavior should be exist [here](https://github.com/mschema/mschema-rpc/tree/master/test)

**Comment by thanpolas** [comment]
How would this be expressed in mschema:

``` js

    properties: {
      id: { type: 'any' },
      callback: {
        type: 'function',
        default: function (err) {
          if (err) {
            queue.emit('error', err);
          }
        }
      }
```

So how is `any` type expressed?
And how can a `default` prop be defined for a `function` type?

**Comment by Marak** [comment]
Input arguments for methods must now be in `function(options, callback)` format. `callback` no longer has to be explicitly defined. `options` is always assumed to be an object hash. You should not define default values as functions.

The schema would be expressed as:

```
 "input": {
   "id": {
     "type": "any"
   }
 }

```

This behavior is defined here: https://github.com/mschema/mschema-rpc

**Comment by Marak** [comment]
I see that `mschema` is currently lacking an `any` type. This is a problem that should be resolved in mschema core. For now you should be able to use `string` type.

**Comment by thanpolas** [comment]
ok i updated the mschema and how methods are exported, plugged everything together, now there are 3 remaining issues:
1. I am not sure about [this property nesting](https://github.com/thanpolas/resource-queue/blob/master/queue.mschema.js#L51-L61), if it's legal and what it actually means, please have a look.
2. I still have a reference problem of [the resource inside the controller](https://github.com/thanpolas/resource-queue/blob/master/lib/queue-methods.js#L57). So `queue` is the Object defined [in `index.js`](https://github.com/thanpolas/resource-queue/blob/master/index.js#L6)... What's the context of the methods? Can i use `this.get()` ?
3. How do i run the tests?

**Comment by thanpolas** [comment]
i also retained the `any` type, waiting for mschema to be updated, should i PR it?

**Comment by Marak** [comment]
To answer your questions
1. Nested properties are well supported. The syntax can be found [here](https://github.com/mschema/mschema/blob/master/test/nested-constraints-test.js) mschema has good test coverage. Use of the keyword `properties` is not needed in mschema.
2. The methods have no context added to them ( by design ). If you need to reference `queue.get` you can require the `queue` itself. Look at how `resource-user` does this ( https://github.com/bigcompany/resource-user/blob/master/lib/auth.js#L4 ) Since Node can resolve circular dependencies a resource method can require it's parent ( the resource ). It's important to do this inside the method, since resource methods will not be available until nextTick 
3. The tests are built with tap. You'll need to rewrite the test file to use new resource api ( `resource.use` is deprecated in favor of `require()` ). Then run the test file with the `node` command.

I wasn't the original author for the queue resource and I can see now it's design is not perfect. Please feel free to simplify it and it's testing code.

**Comment by Marak** [comment]
`any` type needs to be added to mschema. It shouldn't be much code to patch. I'll see if I can add it now. You can probably add a hot-fix on your end to get around it for now.

**Comment by thanpolas** [comment]
ok updated all ... 

i'm having trouble making the tests pass...

i fail to understand what the method `queue.create()` does and where it's defined... it certainly isn't defined in the resource-queue repo... any directions?

**Comment by Marak** [comment]
Persistence methods ( create / get / destroy / etc ) are handled by the
resource engine.

Calling `Resource.persist` will add these methods
https://github.com/bigcompany/resource/blob/master/test/persistence.js

**Comment by thanpolas** [comment]
mode specifically i am getting a TypeError exception "undefined is not a function", the point where it throws is a callback invocation from [this signature](https://github.com/thanpolas/resource-queue/blob/master/lib/queue-methods.js#L55):

```
methods.modify = function modify(id, fn, callback) {
```

apparently `callback` is undefined... i don't know where this is invoked from, how does `queue.create` end up invoking this method?

**Comment by Marak** [comment]
Input arguments for methods must now be in `function(options, callback)` format where options is an object hash. `function(id, fn, callback)` is not valid.

What is the question about create? I don't know where you are referencing `Resource.create` being called.

**Comment by thanpolas** [comment]
So `queue.create()` is [invoked here in the test file](https://github.com/thanpolas/resource-queue/blob/master/test/tests.js#L36) ... there is no `create` method defined anywhere in the repository...

how does it interface with the persistence module? ... investigating, confused....

**Comment by thanpolas** [comment]
wait, so this signature is invalid?

``` js
methods.unshift = function unshift (id, job, callback) {
```

?

**Comment by thanpolas** [comment]
still confused, [i read in user mschema](https://github.com/mschema/user/blob/master/index.js#L56-L63) two properties in a method input...

**Comment by thanpolas** [comment]
ok got it, they are provided in the hash as props

**Comment by Marak** [comment]
No, it is not a valid signature anymore.

Again: In the new resource engine all resource methods **MUST** have a method signature of `function(options, callback)` where options is an object containing properties.

**Comment by thanpolas** [comment]
ok im signing off, to recap there are two issues:
1. Please explain how persistence methods are linked to a resource, queue in our case. I can't understand how `queue.create()` interacts with the queue codebase...
2. The `any` type in mschema... Influenced from Closure jsdocs, the any type is referenced as `*`.

**Comment by Marak** [comment]
1. Persistence methods are added when `Resource.persist` is called. Test coverage is here https://github.com/bigcompany/resource/blob/master/test/persistence.js
2. `any` type has now been added https://github.com/mschema/mschema/commit/dbceb5f09f3aec4c5e8a574d7a70c986e5b7103d

**Comment by thanpolas** [comment]
I have started with the wrong resource, there are still unknowns to me ... please understand i cannot figure out how the persistence methods interact with the current codebase... [This particular method](https://github.com/thanpolas/resource-queue/blob/master/lib/queue-methods.js#L55) keeps failing in the tests with `options.id` being undefined... i can't understand how from `queue.create()` we end up invoking `queue.modify` ... [tests blow up in a mess](https://gist.github.com/thanpolas/47eca84f18ec8d17f678) i have a hard time distinguishing  what blows up on what...

Please publish patched mschema and `resource` package so it'll be available in the `resource-queue` package, hopefully this will make more tests pass...

In the meantime i created a migration script ( #74 ) and migrated another resource, [resource-github](https://github.com/thanpolas/resource-github). It's finished and ready to ship, please review and let me know how you want to handle this, i can move ownership to @bigcompany

**Comment by thanpolas** [comment]
@Marak ping, i'd love to accomplish something before this weekend, xmas will suck me up.

**Comment by Marak** [comment]
This has been done. We've had multiple repos for some time.
